### ISSUE TITLE
pixtype appears off-by-1

### ISSUE THREAD

**Issue by jleibs-zipline** [nathancahill/wkb-raster#1]
https://github.com/nathancahill/wkb-raster/blob/a8368da80661fc0edc08ec8ff8ab29736a136c2d/wkb_raster.py#L146

As far as I can tell, according to the RFC, the -1 here is incorrect and pixtype should simply be:
```
pixtype = (bits & 15)
```

Apologies if I've misunderstood something.

**Comment by nathancahill** [comment]
Hmm, I think you're right. I wrote this a little bit ago, so I'm having trouble remembering the `-1`.

**Comment by nathancahill** [comment]
Did you run into an issue with that? Or do you have an example wkb I could look at?

**Comment by jleibs-zipline** [comment]
Yeah -- was trying to use this to explore some raster data pulled out of a post-gis instance.  The data should be 16-bit signed, but was being loaded as 8-bit unsigned.  Here's an example WKB:
```
010000010000B89A785634323F00B89A78563432BFB3C3D4E5F6FF3C40547698BADCFEEFBF00000000000000000000000000000000E61000000A000A00050000E406E606EC06F106F306F506FC06080711071207E706E506E806E906E806EC06F306FD0607070B07EB06E906E706E706E606E806EB06F306FB060407F306EE06EA06E806E906E706E706EB06EF06F806F606F306EE06EB06EB06E906E606E606E706EC06FD06F806F406F106F206EF06EB06E706E506E40605070007FF06FD06FC06F906F206EB06E606E1060E070C070C070A0706070207FA06F006E906E4061A071807180714070E0708070107F906F106EA062607240722071D071707110709070107FA06F106
```

**Comment by nathancahill** [comment]
Ok, great, I was able to replicate. Want to submit a PR with that change?

**Comment by jleibs-zipline** [comment]
Sure.  Will do as soon as I get a chance.
