### ISSUE TITLE
Writing WKB Raster

### ISSUE THREAD

**Issue by gc-sommer** [nathancahill/wkb-raster#4]
Hi @nathancahill!

Thanks for your work on wkb raster! I've come across a situation where I had to write WKB Raster (without PostGIS database involved) and want to contribute the write function to your repository.
Are you interested?

Best regards,
Johannes

**Comment by nathancahill** [comment]
Excellent. Added you as a contributor.

**Comment by gc-sommer** [comment]
@nathancahill could you update the release on PyPI please?
